[cisco_switches]


[cisco_switches:vars]
ansible_network_os=ios
ansible_connection=network_cli
ansible_user=admin
ansible_password=YOUR_PASSWORD
ansible_become=yes
ansible_become_method=enable
ansible_become_password=ENABLE_PASSWORD
